global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100'
                  '192.168.230.4:9100',
                  '192.168.230.63:9100'
                 ]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'proxmox'
    static_configs:
      - targets: ['192.168.230.11:9221']
    metrics_path: /pve
    params:
      module: [default]

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
            - targets: [
              '192.168.230.4:9100',
              '192.168.230.63:9100'
              ]