version: '2'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data

networks:
  default:
    external:
      name: $DOCKER_MY_NETWORK